export let car_types = [
    {type: 'Tesla'},
    {type: 'Acura'},
    {type: 'Alfa Romero'},
    {type: 'Audi'},
    {type: 'Bentley'},
    {type: 'BMW'},
    {type: 'Buick'},
    {type: 'Cadilac'},
    {type: 'Chevrolet'},
    {type: 'Chrysler'},
    {type: 'Dodge'},
    {type: 'Ferrari'},
    {type: 'Fiat'},
    {type: 'Ford'},
    {type: 'Genesis'},
    {type: 'GMC'},
    {type: 'Honda'},
    {type: 'Hyundai'},
    {type: 'Infiniti'},
    {type: 'Isuzu'},
    {type: 'Jaguar'},
    {type: 'Jeep'},
    {type: 'Kia'},
    {type: 'Lamborghini'},
    {type: 'Land Rover'},
    {type: 'Lexus'},
    {type: 'Lincoln'},
    {type: 'Maserati'},
    {type: 'Mazda'},
    {type: 'Mercedes'},
    {type: 'Mini'},
    {type: 'Mitsbushi'},
    {type: 'Nissan'},
    {type: 'Porsche'},
    {type: 'RAM'},
    {type: 'Rolls-Royce'},
    {type: 'Saturn'},
    {type: 'Subaru'},
    {type: 'Tesla'},
    {type: 'Toyota'},
    {type: 'Volkswagen'},
    {type: 'VOLVO'}
  ];